// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vjuxcfnhkbfknvzoionm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZqdXhjZm5oa2Jma252em9pb25tIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTk3NzE2MDQsImV4cCI6MjA3NTM0NzYwNH0.sURWl6YUV3GywR4_2vfQjUhu63zsOmt3HAAGeoJYk8w";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});